# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggy', '0002_auto_20170302_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='dateReviewed',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='posts',
            name='parseTool',
            field=models.TextField(default=None),
        ),
    ]
