# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggy', '0003_auto_20161208_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='tumorSIze',
            new_name='tumorSize',
        ),
    ]
