# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggy', '0003_annotators_domains_domains_tags_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotators_domains',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
