# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggy', '0004_annotators_domains_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags_keywords',
            name='keywordsList',
        ),
        migrations.AddField(
            model_name='tags_keywords',
            name='keyword',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
