# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggy', '0004_auto_20170204_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotators',
            options={'verbose_name_plural': 'Annotators'},
        ),
        migrations.AlterModelOptions(
            name='annotators_sets',
            options={'verbose_name_plural': 'Annotators sets'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='check_posts',
            options={'verbose_name_plural': 'Check posts'},
        ),
        migrations.AlterModelOptions(
            name='emoticons',
            options={'verbose_name_plural': 'Emoticons'},
        ),
        migrations.AlterModelOptions(
            name='emoticons_tag',
            options={'verbose_name_plural': 'Emoticons tag'},
        ),
        migrations.AlterModelOptions(
            name='forums',
            options={'verbose_name_plural': 'Forums'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='posts_annotators',
            options={'verbose_name_plural': 'Posts annotators'},
        ),
        migrations.AlterModelOptions(
            name='posts_emoticons',
            options={'verbose_name_plural': 'Post emoticons'},
        ),
        migrations.AlterModelOptions(
            name='posts_sets',
            options={'verbose_name_plural': 'Posts sets'},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='sentences',
            options={'verbose_name_plural': 'Sentences'},
        ),
        migrations.AlterModelOptions(
            name='sentences_tags',
            options={'verbose_name_plural': 'Sentences tags'},
        ),
        migrations.AlterModelOptions(
            name='sets',
            options={'verbose_name_plural': 'Sets'},
        ),
        migrations.AlterModelOptions(
            name='signatures',
            options={'verbose_name_plural': 'Signatures'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name_plural': 'Topics'},
        ),
    ]
