# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggy', '0005_auto_20170401_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tagName',
            field=models.CharField(max_length=25),
        ),
    ]
