# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggy', '0007_auto_20170401_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='state',
            field=models.CharField(default='INITIAL', max_length=50),
        ),
    ]
